shopping_tutorial/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using shopping_tutorial.Models;
using shopping_tutorial.Repository;
using Microsoft.EntityFrameworkCore;

namespace shopping_tutorial.Controllers
{
	public class BrandController : Controller
	{
		private DataContext _dataContext;
		public BrandController(DataContext dataContext) { 
			_dataContext = dataContext;
		}
        public async Task<IActionResult> Index(string slug = "")
        {
            BrandModel brand = await _dataContext.Brands
                .FirstOrDefaultAsync(c => c.slug == slug);

            if (brand == null)
            {
              
                return RedirectToAction("Index", new { slug = "" });
            }

            var productsByBrand = await _dataContext.Products
                .Where(p => p.BrandId == brand.Id)
                .OrderByDescending(p => p.Id)
                .ToListAsync();

            return View(productsByBrand);
        }
    }
}

shopping_tutorial/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using shopping_tutorial.Models;
using shopping_tutorial.Repository;
using Microsoft.EntityFrameworkCore;

namespace shopping_tutorial.Controllers
{
	public class CategoryController : Controller
	{
		private DataContext _dataContext;
		public CategoryController(DataContext dataContext) { 
			_dataContext = dataContext;
		}
        public async Task<IActionResult> Index(string slug = "")
        {
            CategoryModel category = await _dataContext.Categories
                .FirstOrDefaultAsync(c => c.slug == slug);

            if (category == null)
            {
              
                return RedirectToAction("Index", new { slug = "" });
            }

            var productsByCat = await _dataContext.Products
                .Where(p => p.CategoryId == category.Id)
                .OrderByDescending(p => p.Id)
                .ToListAsync();

            return View(productsByCat);
        }
    }
}

shopping_tutorial/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using shopping_tutorial.Repository;

namespace shopping_tutorial.Controllers
{
	
	public class ProductController : Controller
	{
		private DataContext _dataContext;
		public ProductController(DataContext dataContext)
		{
			_dataContext = dataContext;
		}
		public IActionResult Index()
		{
			return View();


		}
		public IActionResult Details(int id)
		{	
			//int id = (float)id ?? string.Empty;
			var product = _dataContext.Products.FirstOrDefault(x => x.Id == id);
			return View(product);
		}
	}
}

shopping_tutorial/Repository/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace shopping_tutorial.Repository.Components
{
	public class BrandsViewComponent : ViewComponent
	{
		private readonly DataContext _dataContext;
		public BrandsViewComponent(DataContext dataContext)
		{
			_dataContext = dataContext;
		}
		public async Task<IViewComponentResult> InvokeAsync() => View(await _dataContext.Brands.ToListAsync());

	}
}

shopping_tutorial/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>@ViewData["Title"] - Admin</title>
	<link href="~/css/bootstrap.min.css" rel="stylesheet">
	<link href="~/css/font-awesome.min.css" rel="stylesheet">
	<link href="~/css/prettyPhoto.css" rel="stylesheet">
	<link href="~/css/price-range.css" rel="stylesheet">
	<link href="~/css/animate.css" rel="stylesheet">
	<link href="~/css/main.css" rel="stylesheet">
	<link href="~/css/responsive.css" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="~/js/html5shiv.js"></script>
	<script src="~/js/respond.min.js"></script>
	<![endif]-->

</head><!--/head-->

<body>
	<header id="header">
		<!--header-->
		<div class="header_top">
			<!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		<div class="header-bottom">
			<!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="/" class="active">Home</a></li>
								<li class="dropdown">
									<a asp-controller="Product" asp-action="index" >Product<i class="fa fa-angle-down"></i></a>
								</li>
								<li><a asp-controller="Category" asp-action="index" >Category</a></li>
								<li><a asp-controller="Brand" asp-action="index" >Brand</a></li>
								<li class="dropdown">
									<a href="#">Blog<i class="fa fa-angle-down"></i></a>
									<ul role="menu" class="sub-menu">
										<li><a href="blog.html">Blog List</a></li>
										<li><a href="blog-single.html">Blog Single</a></li>
									</ul>
								</li>
								<li><a href="404.html">404</a></li>
								<li><a href="contact-us.html">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search" />
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	
	</header><!--/header-->
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
	@Html.Partial("_NotificationPartial")
	@RenderBody()
				</div>
			</div>
		</div>
	</section>
	<script src="~/js/jquery.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/jquery.scrollUp.min.js"></script>
	<script src="~/js/price-range.js"></script>
	@* <script src="~/js/jquery.prettyPhoto.js"></script> *@
	@* <script src="~/js/main.js"></script> *@ 
	@await RenderSectionAsync("Scripts",required: false)
</body>
</html>

shopping_tutorial/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null)
{
    <div class="alert  alert-success notification">
        @TempData["success"];
    </div>
}
@if (TempData["error"] != null)
{
    <div class="alert  alert-danger notification">
        @TempData["error"];
    </div>
}

shopping_tutorial/Areas/Admin/Views/Shared/_Sidebars.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="left-sidebar">
	<h2>Category</h2>
	<div class="panel-group category-products" id="accordian">
		<vc:Categories></vc:Categories>
		
	</div><!--/category-products-->

	<div class="brands_products">
		<!--brands_products-->
		<h2>Brands</h2>
		<div class="brands-name">
			<ul class="nav nav-pills nav-stacked">
				<vc:brands></vc:brands>
				
			</ul>
		</div>
	</div><!--/brands_products-->

	<div class="price-range">
		<!--price-range-->
		<h2>Price Range</h2>
		<div class="well text-center">
			<input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
			<b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
		</div>
	</div><!--/price-range-->

	<div class="shipping text-center">
		<!--shipping-->
		<img src="images/home/shipping.jpg" alt="" />
	</div><!--/shipping-->

</div>